version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./src/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_PASSWORD: password
  dummy_start:
    image: alpine:latest
    command: sleep 5
    depends_on:
      postgres:
        condition: service_started
  python36:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.6.15-slim-bullseye
        SETUPTOOLS_VERSION: 59.6.0
        REQUIREMENTS: requirements36.txt
    entrypoint: ./entrypoint.sh
    # tty: true
    # stdin_open: true
    environment:
      - PY_VERSION=3.6
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      dummy_start:
        condition: service_completed_successfully
      postgres:
        condition: service_started
  python37:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.7.17-slim-bookworm
        REQUIREMENTS: requirements37.txt
    entrypoint: ./entrypoint.sh
    environment:
      - PY_VERSION=3.7
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      postgres:
        condition: service_started
      python36:
        condition: service_completed_successfully
  python38:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.8.18-slim-bookworm
    entrypoint: ./entrypoint.sh
    environment:
      - PY_VERSION=3.8
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      postgres:
        condition: service_started
      python37:
        condition: service_completed_successfully
  python39:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.9.18-slim-bookworm
    entrypoint: ./entrypoint.sh
    environment:
      - PY_VERSION=3.9
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      postgres:
        condition: service_started
      python38:
        condition: service_completed_successfully
  python310:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.10.13-slim-bookworm
    entrypoint: ./entrypoint.sh
    environment:
      - PY_VERSION=3.10
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      postgres:
        condition: service_started
      python39:
        condition: service_completed_successfully
  python311:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.11.5-slim-bookworm
    entrypoint: ./entrypoint.sh
    environment:
      - PY_VERSION=3.11
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      postgres:
        condition: service_started
      python310:
        condition: service_completed_successfully
  python312:
    build:
      context: ./docker/
      args:
        DOCKER_IMAGE: python:3.12.0rc2-slim-bookworm
        SETUPTOOLS_VERSION: 68.0.0
        REQUIREMENTS: requirements312.txt
    entrypoint: ./entrypoint.sh
    environment:
      - PY_VERSION=3.12
    volumes:
      - ./src:/code/src
      - ./report:/code/report
    depends_on:
      postgres:
        condition: service_started
      python311:
        condition: service_completed_successfully
  dummy_close:
    image: alpine:latest
    command: sleep 2
    depends_on:
      postgres:
        condition: service_started
      python312:
        condition: service_completed_successfully
